spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wbtkj_chat
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/admin
      authentication-database:
  redis:
    host: localhost
    port: 6379
    password:

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

email:
  hostname: smtp.qq.com
  email-from: 1712683212@qq.com
  au: ezjcvxhvxxvmfajg

server:
  servlet:
    encoding:
      charset: UTF-8


