spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wbtkj_chat?serverTimezone=UTC
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/admin
      authentication-database:
  redis:
    host: localhost
    port: 6379
    password:
  application:
    name: chat-java-wbtkj

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/wbtkj/chat/mapper/*.xml

email:
  hostname: smtp.qq.com
  email-from: 1712683212@qq.com
  au: ezjcvxhvxxvmfajg

server:
  servlet:
    encoding:
      charset: UTF-8
  port: 10317

grpc:
  client:
    grpc-server:
      address: 'static://127.0.0.1:50051'
      negotiationType: plaintext

chatgpt:
  apiKey: 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,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
  apiHost: https://openai.wbtkj.top/

log:
  path: D:/ProgramData/Springbootlog

