spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/wbtkj_chat
    username: postgres
    password: wbtkjjktbw
  data:
    mongodb:
      uri: mongodb://wbtkj:wbtkjjktbw@127.0.0.1:27017/chat-wbtkj
  redis:
    host: 127.0.0.1
    port: 6379
    password: wbtkjjktbw

log:
  path: /var/log/chat-java-wbtkj
  level: info

#cros:
#  allow-host: 147.161.32.40