spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://42.192.145.155:5432/wbtkj_chat
    username: postgres
    password: wbtkjjktbw
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://42.192.145.155:3306/wbtkj_chat?serverTimezone=UTC
#    username: root
#    password: R/oot123
  data:
    mongodb:
      uri: mongodb://wbtkj:wbtkjjktbw@42.192.145.155:27017/chat-wbtkj
      authentication-database:
  redis:
    host: 42.192.145.155
    port: 6379
    password: wbtkjjktbw
  application:
    name: chat-java-wbtkj
  servlet:
    multipart:
      max-file-size: 20MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/wbtkj/chat/mapper/*.xml
  type-handlers-package: com.wbtkj.chat.mapper.typeHandler

email:
  hostname: smtp.163.com
  email-from: wbtkj0317@163.com
  au: VOTLHEUAQTTDAXDZ

server:
  servlet:
    encoding:
      charset: UTF-8
  port: 10317

chatgpt:
  apiHost: https://openai.wbtkj.top/

chat-py-wbtkj:
  apiHost: http://localhost:10318/

log:
  path: D:/ProgramData/Springbootlog
  level: debug