# 该镜像需要依赖的基础镜像
FROM openjdk:8-jdk-slim
# 将当前目录下的jar包复制到docker容器的/目录下
ADD target/*.jar /root/main.jar
# 声明服务运行端口
EXPOSE 10317
# 指定docker容器启动时运行jar包
ENTRYPOINT ["java", "--spring.profiles.active=dev", "-jar","/root/main.jar"]
# 指定维护者的名字
MAINTAINER sizhanyu 773508803@qq.com